/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const FontIcon: typeof import('../shared/components')['FontIcon']
  const Link: typeof import('react-router-dom')['Link']
  const Margin: typeof import('styled-components-spacing')['Margin']
  const NavLink: typeof import('react-router-dom')['NavLink']
  const Outlet: typeof import('react-router-dom')['Outlet']
  const Padding: typeof import('styled-components-spacing')['Padding']
  const ReactDOM: typeof import('react-dom/client')['ReactDOM']
  const RouterProvider: typeof import('react-router-dom')['RouterProvider']
  const StrictMode: typeof import('react')['StrictMode']
  const StyleSheetManager: typeof import('styled-components')['StyleSheetManager']
  const Suspense: typeof import('react')['Suspense']
  const ThemeProvider: typeof import('styled-components')['ThemeProvider']
  const Trans: typeof import('react-i18next')['Trans']
  const Translation: typeof import('react-i18next')['Translation']
  const axios: typeof import('axios')['default']
  const cloneElement: typeof import('react')['cloneElement']
  const create: typeof import('zustand')['create']
  const createBrowserRouter: typeof import('react-router-dom')['createBrowserRouter']
  const createContext: typeof import('react')['createContext']
  const createGlobalStyle: typeof import('styled-components')['createGlobalStyle']
  const createRef: typeof import('react')['createRef']
  const createRoot: typeof import('react-dom/client')['createRoot']
  const createStore: typeof import('../shared/utils')['createStore']
  const css: typeof import('styled-components')['css']
  const forwardRef: typeof import('react')['forwardRef']
  const generateSelectors: typeof import('../shared/utils')['generateSelectors']
  const get: typeof import('lodash-es')['get']
  const has: typeof import('lodash-es')['has']
  const i18nInstance: typeof import('i18next')['default']
  const initReactI18next: typeof import('react-i18next')['initReactI18next']
  const isString: typeof import('lodash-es')['isString']
  const keyframes: typeof import('styled-components')['keyframes']
  const lazy: typeof import('react')['lazy']
  const logOut: typeof import('../api/auth')['logOut']
  const memo: typeof import('react')['memo']
  const my: typeof import('styled-components-spacing')['my']
  const px: typeof import('styled-components-spacing')['px']
  const resetAllStores: typeof import('../shared/utils')['resetAllStores']
  const signIn: typeof import('../api/auth')['signIn']
  const startTransition: typeof import('react')['startTransition']
  const styled: typeof import('styled-components')['default']
  const translate: typeof import('../shared/utils')['translate']
  const updateLocale: typeof import('i18next')['changeLanguage']
  const useBeforeUnload: typeof import('react-router-dom')['useBeforeUnload']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useCookies: typeof import('../hooks/use-cookies')['default']
  const useDateTime: typeof import('../hooks/use-date-time')['default']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useHttpRequest: typeof import('../hooks/use-http-request')['default']
  const useI18n: typeof import('i18next')['use']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useIsLoggedIn: typeof import('../hooks/use-is-logged-in')['default']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useLocation: typeof import('react-router-dom')['useLocation']
  const useMatch: typeof import('react-router-dom')['useMatch']
  const useMemo: typeof import('react')['useMemo']
  const useMultipleRequests: typeof import('../hooks/use-request')['useMultipleRequests']
  const useNavigate: typeof import('react-router-dom')['useNavigate']
  const useParams: typeof import('react-router-dom')['useParams']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRequest: typeof import('../hooks/use-request')['useRequest']
  const useSearchParams: typeof import('react-router-dom')['useSearchParams']
  const useState: typeof import('react')['useState']
  const useStorage: typeof import('../hooks/use-storage')['default']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useToast: typeof import('../hooks/use-toast')['default']
  const useTransition: typeof import('react')['useTransition']
  const useTranslation: typeof import('react-i18next')['useTranslation']
  const windowRedirect: typeof import('../shared/utils')['windowRedirect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FunctionComponent, ReactNode, ReactElement, Key, MouseEvent as ReactMouseEvent, KeyboardEvent as ReactKeyboardEvent, ComponentType, ComponentProps, ChangeEvent, Ref, RefObject, Dispatch, SetStateAction, CSSProperties } from 'react'
  // @ts-ignore
  export type { DefaultTheme } from 'styled-components'
  // @ts-ignore
  export type { StoreApi, UseBoundStore, StateCreator } from 'zustand'
  // @ts-ignore
  export type { AxiosInstance, AxiosResponse, AxiosError, InternalAxiosRequestConfig, AxiosRequestConfig, AxiosPromise } from 'axios'
}
